# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from imu_nav_ml/ListOfLists.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import imu_nav_ml.msg

class ListOfLists(genpy.Message):
  _md5sum = "fae0d37fb284617a626d94525abd3508"
  _type = "imu_nav_ml/ListOfLists"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """PythonList[] matrix

================================================================================
MSG: imu_nav_ml/PythonList
float64[] row
"""
  __slots__ = ['matrix']
  _slot_types = ['imu_nav_ml/PythonList[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       matrix

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ListOfLists, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.matrix is None:
        self.matrix = []
    else:
      self.matrix = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.matrix)
      buff.write(_struct_I.pack(length))
      for val1 in self.matrix:
        length = len(val1.row)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(struct.Struct(pattern).pack(*val1.row))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.matrix is None:
        self.matrix = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.matrix = []
      for i in range(0, length):
        val1 = imu_nav_ml.msg.PythonList()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.row = s.unpack(str[start:end])
        self.matrix.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.matrix)
      buff.write(_struct_I.pack(length))
      for val1 in self.matrix:
        length = len(val1.row)
        buff.write(_struct_I.pack(length))
        pattern = '<%sd'%length
        buff.write(val1.row.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.matrix is None:
        self.matrix = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.matrix = []
      for i in range(0, length):
        val1 = imu_nav_ml.msg.PythonList()
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        pattern = '<%sd'%length
        start = end
        s = struct.Struct(pattern)
        end += s.size
        val1.row = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
        self.matrix.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
