// Generated by gencpp from file imu_nav_ml/ImuNavPrediction.msg
// DO NOT EDIT!


#ifndef IMU_NAV_ML_MESSAGE_IMUNAVPREDICTION_H
#define IMU_NAV_ML_MESSAGE_IMUNAVPREDICTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Vector3.h>

namespace imu_nav_ml
{
template <class ContainerAllocator>
struct ImuNavPrediction_
{
  typedef ImuNavPrediction_<ContainerAllocator> Type;

  ImuNavPrediction_()
    : header()
    , position()
    , velocity()
    , position_error_3d(0.0)
    , velocity_error_3d(0.0)
    , inference_time(0.0)  {
    }
  ImuNavPrediction_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(_alloc)
    , velocity(_alloc)
    , position_error_3d(0.0)
    , velocity_error_3d(0.0)
    , inference_time(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef float _position_error_3d_type;
  _position_error_3d_type position_error_3d;

   typedef float _velocity_error_3d_type;
  _velocity_error_3d_type velocity_error_3d;

   typedef float _inference_time_type;
  _inference_time_type inference_time;





  typedef boost::shared_ptr< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> const> ConstPtr;

}; // struct ImuNavPrediction_

typedef ::imu_nav_ml::ImuNavPrediction_<std::allocator<void> > ImuNavPrediction;

typedef boost::shared_ptr< ::imu_nav_ml::ImuNavPrediction > ImuNavPredictionPtr;
typedef boost::shared_ptr< ::imu_nav_ml::ImuNavPrediction const> ImuNavPredictionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator1> & lhs, const ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.position == rhs.position &&
    lhs.velocity == rhs.velocity &&
    lhs.position_error_3d == rhs.position_error_3d &&
    lhs.velocity_error_3d == rhs.velocity_error_3d &&
    lhs.inference_time == rhs.inference_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator1> & lhs, const ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_nav_ml

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a3de14811f7c35ef90a6a889e58a171";
  }

  static const char* value(const ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a3de14811f7c35eULL;
  static const uint64_t static_value2 = 0xf90a6a889e58a171ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_nav_ml/ImuNavPrediction";
  }

  static const char* value(const ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"geometry_msgs/Point position\n"
"geometry_msgs/Vector3 velocity\n"
"float32 position_error_3d\n"
"float32 velocity_error_3d\n"
"float32 inference_time\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.position_error_3d);
      stream.next(m.velocity_error_3d);
      stream.next(m.inference_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ImuNavPrediction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_nav_ml::ImuNavPrediction_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "position_error_3d: ";
    Printer<float>::stream(s, indent + "  ", v.position_error_3d);
    s << indent << "velocity_error_3d: ";
    Printer<float>::stream(s, indent + "  ", v.velocity_error_3d);
    s << indent << "inference_time: ";
    Printer<float>::stream(s, indent + "  ", v.inference_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_NAV_ML_MESSAGE_IMUNAVPREDICTION_H
