// Generated by gencpp from file imu_nav_ml/ListOfLists.msg
// DO NOT EDIT!


#ifndef IMU_NAV_ML_MESSAGE_LISTOFLISTS_H
#define IMU_NAV_ML_MESSAGE_LISTOFLISTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <imu_nav_ml/PythonList.h>

namespace imu_nav_ml
{
template <class ContainerAllocator>
struct ListOfLists_
{
  typedef ListOfLists_<ContainerAllocator> Type;

  ListOfLists_()
    : matrix()  {
    }
  ListOfLists_(const ContainerAllocator& _alloc)
    : matrix(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::imu_nav_ml::PythonList_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::imu_nav_ml::PythonList_<ContainerAllocator> >> _matrix_type;
  _matrix_type matrix;





  typedef boost::shared_ptr< ::imu_nav_ml::ListOfLists_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_nav_ml::ListOfLists_<ContainerAllocator> const> ConstPtr;

}; // struct ListOfLists_

typedef ::imu_nav_ml::ListOfLists_<std::allocator<void> > ListOfLists;

typedef boost::shared_ptr< ::imu_nav_ml::ListOfLists > ListOfListsPtr;
typedef boost::shared_ptr< ::imu_nav_ml::ListOfLists const> ListOfListsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_nav_ml::ListOfLists_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_nav_ml::ListOfLists_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_nav_ml::ListOfLists_<ContainerAllocator1> & lhs, const ::imu_nav_ml::ListOfLists_<ContainerAllocator2> & rhs)
{
  return lhs.matrix == rhs.matrix;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_nav_ml::ListOfLists_<ContainerAllocator1> & lhs, const ::imu_nav_ml::ListOfLists_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_nav_ml

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_nav_ml::ListOfLists_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_nav_ml::ListOfLists_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_nav_ml::ListOfLists_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_nav_ml::ListOfLists_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_nav_ml::ListOfLists_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_nav_ml::ListOfLists_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_nav_ml::ListOfLists_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fae0d37fb284617a626d94525abd3508";
  }

  static const char* value(const ::imu_nav_ml::ListOfLists_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfae0d37fb284617aULL;
  static const uint64_t static_value2 = 0x626d94525abd3508ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_nav_ml::ListOfLists_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_nav_ml/ListOfLists";
  }

  static const char* value(const ::imu_nav_ml::ListOfLists_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_nav_ml::ListOfLists_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PythonList[] matrix\n"
"\n"
"================================================================================\n"
"MSG: imu_nav_ml/PythonList\n"
"float64[] row\n"
;
  }

  static const char* value(const ::imu_nav_ml::ListOfLists_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_nav_ml::ListOfLists_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.matrix);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ListOfLists_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_nav_ml::ListOfLists_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_nav_ml::ListOfLists_<ContainerAllocator>& v)
  {
    s << indent << "matrix[]" << std::endl;
    for (size_t i = 0; i < v.matrix.size(); ++i)
    {
      s << indent << "  matrix[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::imu_nav_ml::PythonList_<ContainerAllocator> >::stream(s, indent + "    ", v.matrix[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_NAV_ML_MESSAGE_LISTOFLISTS_H
