// Generated by gencpp from file imu_nav_ml/PythonList.msg
// DO NOT EDIT!


#ifndef IMU_NAV_ML_MESSAGE_PYTHONLIST_H
#define IMU_NAV_ML_MESSAGE_PYTHONLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace imu_nav_ml
{
template <class ContainerAllocator>
struct PythonList_
{
  typedef PythonList_<ContainerAllocator> Type;

  PythonList_()
    : row()  {
    }
  PythonList_(const ContainerAllocator& _alloc)
    : row(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _row_type;
  _row_type row;





  typedef boost::shared_ptr< ::imu_nav_ml::PythonList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_nav_ml::PythonList_<ContainerAllocator> const> ConstPtr;

}; // struct PythonList_

typedef ::imu_nav_ml::PythonList_<std::allocator<void> > PythonList;

typedef boost::shared_ptr< ::imu_nav_ml::PythonList > PythonListPtr;
typedef boost::shared_ptr< ::imu_nav_ml::PythonList const> PythonListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_nav_ml::PythonList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_nav_ml::PythonList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_nav_ml::PythonList_<ContainerAllocator1> & lhs, const ::imu_nav_ml::PythonList_<ContainerAllocator2> & rhs)
{
  return lhs.row == rhs.row;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_nav_ml::PythonList_<ContainerAllocator1> & lhs, const ::imu_nav_ml::PythonList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_nav_ml

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_nav_ml::PythonList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_nav_ml::PythonList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_nav_ml::PythonList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_nav_ml::PythonList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_nav_ml::PythonList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_nav_ml::PythonList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_nav_ml::PythonList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f476b09ffe66a6e073b86346f9b64b0";
  }

  static const char* value(const ::imu_nav_ml::PythonList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f476b09ffe66a6eULL;
  static const uint64_t static_value2 = 0x073b86346f9b64b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_nav_ml::PythonList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_nav_ml/PythonList";
  }

  static const char* value(const ::imu_nav_ml::PythonList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_nav_ml::PythonList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] row\n"
;
  }

  static const char* value(const ::imu_nav_ml::PythonList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_nav_ml::PythonList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.row);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PythonList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_nav_ml::PythonList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_nav_ml::PythonList_<ContainerAllocator>& v)
  {
    s << indent << "row[]" << std::endl;
    for (size_t i = 0; i < v.row.size(); ++i)
    {
      s << indent << "  row[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.row[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_NAV_ML_MESSAGE_PYTHONLIST_H
